# Site settings
title: ✨不羁个P
email: pingpong@yeah.net
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/index" # the subpath of your site, e.g. /blog/
url: "https://www.bujigep.me/" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown:
